Language: node_js
node_js:
 - 13


services:
 - docker

# Pre-testing installs
install:
 - echo "nothing needs to be installed"

# Scripts to be run such as test
before_script:
 - echo "no tests"


script:
 - docker --version # print the version for logging
 - docker build -t reverseproxy ./reverseproxy
 - docker build -t udagram-api-user ./udagram-api-user
 - docker build -t udagram-api-feed ./udagram-api-feed
 - docker build -t udagram-frontend ./udagram-frontend
 - docker tag reverseproxy docker0057/reverseproxy:v1
 - docker tag udagram-api-user docker0057/udagram-api-user:v1
 - docker tag udagram-api-feed docker0057/udagram-api-feed:v1
 - docker tag udagram-frontend docker0057/udagram-frontend:v1


after_success:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker push docker0057/reverseproxy:v1
 - docker push docker0057/udagram-api-user:v1
 - docker push docker0057/udagram-api-feed:v1
 - docker push docker0057/udagram-frontend:v1



